const tips = [{
        id: 1,
        title: 'Z luna Paul McBeth Tour...',
        type: 'PA',
        experience: 'A',
        price: '239',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 2,
        title: 'Z luna Paul McBeth Tour...',
        type: 'MD',
        experience: 'E',
        price: '199',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 3,
        title: 'Z luna Paul McBeth Tour...',
        type: 'DD',
        experience: 'N',
        price: '239',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 4,
        title: 'Z luna Paul McBeth Tour...',
        type: 'FD',
        experience: 'A',
        price: '159',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 5,
        title: 'Z luna Paul McBeth Tour...',
        type: 'PA',
        experience: 'A',
        price: '119',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 6,
        title: 'Z luna Paul McBeth Tour...',
        type: 'FD',
        experience: 'E',
        price: '239',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 7,
        title: 'Z luna Paul McBeth Tour...',
        type: 'MD',
        experience: 'A',
        price: '179',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 8,
        title: 'Z luna Paul McBeth Tour...',
        type: 'PA',
        experience: 'N',
        price: '159',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 9,
        title: 'Z luna Paul McBeth Tour...',
        type: 'FD',
        experience: 'N',
        price: '239',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 10,
        title: 'Z luna Paul McBeth Tour...',
        type: 'MD',
        experience: 'A',
        price: '169',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 11,
        title: 'Z luna Paul McBeth Tour...',
        type: 'DD',
        experience: 'E',
        price: '129',
        image: require('../assets/discpicture1.png'),
    },
    {
        id: 12,
        title: 'Z luna Paul McBeth Tour...',
        type: 'PA',
        experience: 'A',
        price: '239',
        image: require('../assets/discpicture1.png'),
    },
]

export default tips;